### ISSUE TITLE
Add generation support for srv and action files

### ISSUE THREAD

**Issue by aeon9** [pinorobotics/msgmonster#2]
Currently msgmonster generates classes only for msg files, it would be nice to support srv, action files too

**Comment by marlow-fawn** [comment]
Hello! Are there currently any plans for this? Would love to use the [Spot ROS2 package](https://github.com/bdaiinstitute/spot_ros2) with jrosclient, but it has a number of custom services and actions that would add a lot of overhead to write by hand.

**Comment by lambdaprime** [comment]
Hi @marlow-fawn,

Thanks for using **jrosclient**

We currently occupied with support for ROS2 Jazzy Jalisco.
Once it is ready we are going to prioritize this (ETA end of July)

Regards,

**Comment by aeon9** [comment]
Hi @marlow-fawn ,

We just published a [new v5 release](https://github.com/pinorobotics/msgmonster/blob/main/msgmonster/release/CHANGELOG.md) where this feature is added.

Regards,
