### ISSUE TITLE
Hanging on Message generation

### ISSUE THREAD

**Issue by marlow-fawn** [pinorobotics/msgmonster#3]
Having an issue when running on bosdyn_api_msgs. It appears to hang on the following message:

[NetworkComputeResponse.txt](https://github.com/user-attachments/files/16415886/NetworkComputeResponse.txt)

This also happens when trying to build just that message.
I don't actually need this message, so if there's some way to ignore certain messages in a package that would be a sufficient workaround for now.

**Comment by aeon9** [comment]
Hi,

Thanks for using **jrosclient**

We added debug mode support.

Could you please try [prerelease version](https://github.com/pinorobotics/msgmonster/releases) with option "-d" and send us "msgmonster-debug.log" file under system temporary directory.

Regards,

**Comment by aeon9** [comment]
Hi @marlow-fawn ,

We added improvements for ROS constants and could generate Java class for NetworkComputeResponse.txt
Could you please try new [prerelease version](https://github.com/pinorobotics/msgmonster/releases).

If it still hangs please use option "-d" and send us "msgmonster-debug.log" file under system temporary directory.

Additionally we added "-exclude" option support (see README for details how to use it) so you can skip any problematic messages.

Regards,

**Comment by marlow-fawn** [comment]
Thanks so much! should have time to test it before the weekend.

**Comment by marlow-fawn** [comment]
This is all that's written to the debug file before hanging. 
[msgmonster-debug.log](https://github.com/user-attachments/files/16533104/msgmonster-debug.log)

`

**Comment by aeon9** [comment]
Hi @marlow-fawn ,

Thank you for sending the log.

Based on it could you please run: 
```
ros2 interface show bosdyn_api_msgs/msg/NetworkComputeResponse && echo $?
```

And send the output here.

Additionally when msgmonster hangs could you please run:

```
jstack <msgmonster_PID> >> stack
```

And repeat same command 3 times with 5sec intervals. Then please send "stack" file as well.

Regards,

**Comment by marlow-fawn** [comment]
The exit status is 0.

Here's the stack file:
[stack.txt](https://github.com/user-attachments/files/16561666/stack.txt)

**Comment by aeon9** [comment]
Hi @marlow-fawn,

The fix is ready and will be included in the next version we plan to release.
Until then you can use [prerelease version](https://github.com/pinorobotics/msgmonster/releases)

Regards,

**Comment by aeon9** [comment]
Hi,

We just published a [new v6 release](https://github.com/pinorobotics/msgmonster/blob/main/msgmonster/release/CHANGELOG.md) where this issue is fixed.

Regards,
