### ISSUE TITLE
Fix TimeMessage/Time mismatch

### ISSUE THREAD

**Issue by marlow-fawn** [pinorobotics/msgmonster#4]
msgmonster automatically adds:

`import id.jrosmessages.builtin_interfaces.TimeMessage;`
instead of 
`import id.jrosmessages.primitives.Time;`

Unsure if the proper solution would be to to make an exception in msgmonster, or update jrosmessages to match the actual ROS package name better.

**Comment by aeon9** [comment]
Hi,

Thanks for using **jrosclient**

The fix is ready and will be included in the next version we plan to release.
Until then you can use [prerelease version](https://github.com/pinorobotics/msgmonster/releases)

Regards,

**Comment by aeon9** [comment]
Hi,

We just published a [new v6 release](https://github.com/pinorobotics/msgmonster/blob/main/msgmonster/release/CHANGELOG.md) where this issue is fixed.

Regards,
