### ISSUE TITLE
Service generation errors

### ISSUE THREAD

**Issue by marlow-fawn** [pinorobotics/msgmonster#5]
1. `interfaceType = RosInterfaceType.SERVICE` should be added to `@MessageMetadata`
2. Service `String NAME` name should be updated to `[package]/[serviceName]**Service**[Response/Requset]`.

**Comment by aeon9** [comment]
Hi @marlow-fawn ,

Thanks for using **jrosclient**

We are working on a fix and provide it early next week.

Regards,

**Comment by aeon9** [comment]
Hi,

The fix is ready and will be included in the next version we plan to release.
Until then you can use [prerelease version](https://github.com/pinorobotics/msgmonster/releases)

Regards,

**Comment by aeon9** [comment]
Hi,

We just published a [new v6 release](https://github.com/pinorobotics/msgmonster/blob/main/msgmonster/release/CHANGELOG.md) where this issue is fixed.

Regards,
